### ISSUE TITLE
Build fails with "Command PhaseScriptExecution failed with a nonzero exit code"

### ISSUE THREAD

**Issue by tommythorn** [fernandotcl/TinyEMU-iOS#1]
I have never used Xcode before so I may be making a simple mistake, but I succeeded in creating the `TinyEMU-iOS.xcodeproj` and opening, changing the Team and Bundle Identifier, attaching my phone, and getting a signing certificate.  However hitting run hits the following issues:

<img width="268" alt="Screen Shot 2020-05-26 at 00 37 21" src="https://user-images.githubusercontent.com/862616/82873272-1a0f4b80-9ee9-11ea-86c4-351e3cc23c42.png">

It appears the real issues is 

<img width="471" alt="Screen Shot 2020-05-26 at 00 38 11" src="https://user-images.githubusercontent.com/862616/82873357-3d39fb00-9ee9-11ea-85a1-10383e0b44f3.png">

**Comment by fernandotcl** [comment]
Sounds like you forgot to initialize the Git submodules. Try running `git submodule update --init`. (I guess I should probably add that to the README).

**Comment by tommythorn** [comment]
Ok, starting over with the submodules.  When I open TinyEMU-iOS.xcodeproj, target my physical phone and hit Run I get "Build Succeed" and nothing happens.  When I explicitly try to pick TinyEMU-iOS and hit run I get Build Failed, it complains `npm: command not found`.  I'm guessing it's another build dependency that needs to be mentioned in the documentation?  You installed that with Home Brew?

**Comment by fernandotcl** [comment]
Indeed, for earlier versions of TinyEMU-iOS, you needed node. As of yesterday, this is no longer the case, so you should be good once you update.

**Comment by tommythorn** [comment]
I got through all the build dependencies 10 days ago, but stuck on deploying to actual hardware - it fails and the details are

> Details
> 
> Unable to install "TinyEMU-iOS"
> Domain: com.apple.dt.MobileDeviceErrorDomain
> Code: -402620383
> --
> The maximum number of apps for free development profiles has been reached.
> ...

Links on the Intertubes suggests waiting a week, but that didn't seem to help.
Any suggestions before I sacrifice a pound of flesh?
EDIT: In case it wasn't obvious, I don't compile any other iOS apps.

**Comment by fernandotcl** [comment]
Sorry, code signing without a developer ID is a bit of a black box. You might want to ask around in Apple's support forums, it's not really an issue with TinyEMU-iOS.
